apiVersion: v1
kind: Service
metadata:
  name: billing-service
spec:
  selector:
    app: billing-service
  type: NodePort
  ports:
    - protocol: TCP
      port: 4001
      targetPort: 4001
      nodePort: 30070
      name: service
