services:
  gogs:
    build: gogs/
    image: host.docker.internal:5000/gogs:local
  jenkins:
    build: jenkins/
    image: host.docker.internal:5000/jenkins:local
  setup:
    build:
      context: .
      dockerfile: ./setup/Dockerfile
    image: host.docker.internal:5000/setup:local
  delivery-db:
    build:
      context: .
      dockerfile: ./delivery-db/Dockerfile
    image: host.docker.internal:5000/delivery-db:local