services:
  api-gateway:
    image: nginx:1.27.1
    ports:
      - "6060:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  pact:
    image: pactfoundation/pact-broker:2.123.0-pactbroker2.112.0
    ports:
    - "5050:9292"
    environment:
    - PACT_BROKER_BASIC_AUTH_ENABLED=false
    - PACT_BROKER_ALLOW_PUBLIC_READ=true
    - PACT_BROKER_DATABASE_ADAPTER=sqlite
    - PACT_BROKER_WEBHOOK_SCHEME_WHITELIST=http
    - PACT_BROKER_WEBHOOK_HTTP_METHOD_WHITELIST=GET
    - PACT_BROKER_WEBHOOK_HOST_WHITELIST=jenkins
  gogs:
    build: gogs/
    ports:
    - "3030:3000"
  gogs-db:
    image: postgres:18.2-bookworm
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_PASSWORD=g0g5db
  jenkins:
    build: jenkins/
    ports:
    - "4040:8080"
  setup:
    build:
      context: .
      dockerfile: ./setup/Dockerfile
  prod:
    build: server/
    ports:
    - 8181:8081
    - 8182:8082
    - 8183:8083
    - 8184:8084
    environment:
    - PASSWORD_ACCESS=true
    - USER_PASSWORD=jenkins
    - USER_NAME=jenkins
  test:
    build: server/
    ports:
    - 8281:8081
    - 8282:8082
    - 8283:8083
    - 8284:8084
    environment:
    - PASSWORD_ACCESS=true
    - USER_PASSWORD=jenkins
    - USER_NAME=jenkins
  delivery-db:
    image: postgres:18.2-bookworm
    environment:
    - POSTGRES_DB=postgres
    - POSTGRES_USER=delivery-service
    - POSTGRES_PASSWORD=delivery-password
    volumes:
    - ./delivery-service/src/main/resources/sql:/docker-entrypoint-initdb.d
  delivery-db-test:
    image: postgres:18.2-bookworm
    environment:
    - POSTGRES_DB=postgres
    - POSTGRES_USER=delivery-service
    - POSTGRES_PASSWORD=delivery-password
    volumes:
    - ./delivery-service/src/main/resources/sql:/docker-entrypoint-initdb.d
