services:
  customer-service:
    build: customer-service/
    ports:
      - "8181:8080"
    environment:
      - BILLING_SERVICE_URL=http://billing-service:8080
      - DELIVERY_SERVICE_URL=http://delivery-service:8080

  billing-service:
    build: billing-service/
    container_name: billing-service
    ports:
      - "8182:8080"

  delivery-service:
    build: delivery-service/
    container_name: delivery-service
    ports:
      - "8183:8080"
    environment:
      - ADDRESS_VALIDATION_SERVICE_URL=http://address-validation-service:8080

  address-validation-service:
    build: address-validation-service/
    container_name: address-validation_service
    ports:
      - "8184:8080"

  api-gateway:
    image: nginx:1.27.1
    ports:
      - "6060:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  pact:
    image: pactfoundation/pact-broker:2.123.0-pactbroker2.112.0
    ports:
    - "5050:9292"
    environment:
    - PACT_BROKER_BASIC_AUTH_ENABLED=false
    - PACT_BROKER_ALLOW_PUBLIC_READ=true
    - PACT_BROKER_DATABASE_ADAPTER=sqlite
    - PACT_BROKER_WEBHOOK_SCHEME_WHITELIST=http
    - PACT_BROKER_WEBHOOK_HTTP_METHOD_WHITELIST=GET
    - PACT_BROKER_WEBHOOK_HOST_WHITELIST=jenkins
  gogs:
    build: gogs/
    ports:
    - "3030:3000"
  gogs-db:
    image: postgres:18.2-bookworm
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_PASSWORD=g0g5db
  jenkins:
    build: jenkins/
    ports:
    - "4040:8080"
  setup:
    build:
      context: .
      dockerfile: ./setup/Dockerfile
  prod:
    build: server/
    environment:
    - PASSWORD_ACCESS=true
    - USER_PASSWORD=jenkins
    - USER_NAME=jenkins
  test:
    build: server/
    environment:
    - PASSWORD_ACCESS=true
    - USER_PASSWORD=jenkins
    - USER_NAME=jenkins
  delivery-db:
    image: postgres:18.2-bookworm
    environment:
    - POSTGRES_DB=postgres
    - POSTGRES_USER=delivery-service
    - POSTGRES_PASSWORD=delivery-password
    volumes:
    - ./delivery-service/src/main/resources/sql:/docker-entrypoint-initdb.d
  delivery-db-test:
    image: postgres:18.2-bookworm
    environment:
    - POSTGRES_DB=postgres
    - POSTGRES_USER=delivery-service
    - POSTGRES_PASSWORD=delivery-password
    volumes:
    - ./delivery-service/src/main/resources/sql:/docker-entrypoint-initdb.d
  customer-client:
    build:
      context: customer-client/
      args:
        - VITE_API_URL=http://localhost:8181
    container_name: customer-client
    ports:
      - "3000:80"
    depends_on:
      - customer-service

  swagger-ui:
    image: swaggerapi/swagger-ui:v5.17.7
    volumes:
      - "./swagger-ui:/usr/share/nginx/html/doc"
    environment:
      API_URL: "doc/openapi.yaml"

  wiremock:
    image: wiremock/wiremock:3.5.4
    volumes:
      - "./wiremock:/home/wiremock"
    ports:
      - "7070:8080"

  hurl:
    image: ghcr.io/orange-opensource/hurl:4.3.0
    command: "--retry 5 --test /home/address-1.0.hurl /home/address-1.1.hurl /home/address-2.0.hurl"
    volumes:
      - "./hurl:/home"
    depends_on:
      - wiremock

