apiVersion: apps/v1
kind: Deployment
metadata:
  name: address-validation-deployment
  labels:
    app: address-validation-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: address-validation-service
  template:
    metadata:
      labels:
        app: address-validation-service
    spec:
      containers:
        - name: address-validation
          image: address-validation:latest
          ports:
            - containerPort: 4003
              name: http
