apiVersion: v1
kind: Service
metadata:
  name: address-validation-service
spec:
  selector:
    app: address-validation-service
  type: NodePort
  ports:
    - protocol: TCP
      port: 4003
      targetPort: 4003
      nodePort: 30090
      name: service
