#!/usr/bin/env groovy
pipeline {
    agent any

    parameters {
        booleanParam(name: 'verifyPacts', defaultValue: false, description: 'should this job just run to verify pacts from a consumer')
    }

    options {
        disableConcurrentBuilds()
    }

    environment {
        SNAPSHOT_VERSION = readMavenPom().getVersion()
        LAST_COMMIT_MESSAGE = "${currentBuild.changeSets.size() == 0 ? 'update version to ' : currentBuild.changeSets[currentBuild.changeSets.size() - 1].items.length == 0 ? 'update version to ' : currentBuild.changeSets[currentBuild.changeSets.size() - 1].items[currentBuild.changeSets[currentBuild.changeSets.size() - 1].items.length - 1].msg}"
        PERFORM_RELEASE = "${env.SNAPSHOT_VERSION.contains('-SNAPSHOT') && env.BRANCH_NAME == 'main' && !env.LAST_COMMIT_MESSAGE.startsWith('update version to ')}"
        RELEASE_VERSION = "${env.SNAPSHOT_VERSION.contains('-SNAPSHOT') ? env.SNAPSHOT_VERSION.substring(0, env.SNAPSHOT_VERSION.lastIndexOf('-SNAPSHOT')) : SNAPSHOT_VERSION}"
        VERSION = "${env.BRANCH_NAME == 'main' && !env.LAST_COMMIT_MESSAGE.startsWith('update version to ') ? env.RELEASE_VERSION : env.SNAPSHOT_VERSION}"
        ROOT_DIRECTORY = "${params.verifyPacts == true && env.BRANCH_NAME == 'main' && env.SNAPSHOT_VERSION.endsWith("-SNAPSHOT") ? 'target/checkout' : '.'}"
    }

    triggers {
        pollSCM("* * * * *")
    }

    stages {
        stage ('Compile') {
            when {
                anyOf {
                    not {
                        branch 'main'
                    }
                    environment name: 'PERFORM_RELEASE', value: 'true'
                    expression {
                        params.verifyPacts == true
                    }
                }
            }
            steps {
                echo "Building version ${env.VERSION}"
                script {
                    if (params.verifyPacts == true && env.BRANCH_NAME == 'main' && env.SNAPSHOT_VERSION.endsWith("-SNAPSHOT")) {
                        int previousRevision = Integer.parseInt(env.RELEASE_VERSION.substring(env.RELEASE_VERSION.lastIndexOf(".") + 1)) - 1
                        if (previousRevision >= 0) {
                            previousVersion = RELEASE_VERSION.substring(0, env.RELEASE_VERSION.lastIndexOf(".")) + "." + previousRevision
                            sh "mvn scm:checkout -DscmVersionType=tag -DscmVersion=${previousVersion}"
                            echo "Testing against version ${previousVersion}"
                        }
                    } else if (env.PERFORM_RELEASE.equals('true') && !env.RELEASE_VERSION.equals(env.SNAPSHOT_VERSION)) {
                        sh "mvn versions:set -DnewVersion=${env.RELEASE_VERSION} -B"
                        sh "sed -i 's/${env.SNAPSHOT_VERSION}/${env.RELEASE_VERSION}/g' deployment/overlays/prod/kustomization.yaml"
                    } else {
                        sh "sed -i 's/${env.SNAPSHOT_VERSION}/${env.GIT_COMMIT}/g' deployment/overlays/test/kustomization.yaml"
                    }
                }
                sh """
                    cd ${ROOT_DIRECTORY}
                    mvn clean test-compile -B
                """
            }
        }
        stage ('Test') {
            when {
                anyOf {
                    not {
                        branch 'main'
                    }
                    environment name: 'PERFORM_RELEASE', value: 'true'
                    expression {
                        params.verifyPacts == true
                    }
                }
            }
            steps {
                sh """
                    cd ${ROOT_DIRECTORY}
                    mvn test -DpactBroker.url=http://pact-service:8080 -Dpact.verifier.publishResults=true -B
                """
            }
        }
        stage ('Test providers') {
            when {
                anyOf {
                    not {
                        branch 'main'
                    }
                    environment name: 'PERFORM_RELEASE', value: 'true'
                }
                expression {
                    params.verifyPacts == false
                }
            }
            steps {
                sh 'mvn pact:publish -DpactBroker.url=http://pact-service:8080 -Dpact.verifier.publishResults=true -B'
                build job: "address-validation-service/${env.BRANCH_NAME}", parameters: [booleanParam(name: 'verifyPacts', value: true)]
            }
        }
        stage ('Package') {
            when {
                anyOf {
                    not {
                        branch 'main'
                    }
                    environment name: 'PERFORM_RELEASE', value: 'true'
                }
                expression {
                    params.verifyPacts == false
                }
            }
            steps {
                sh 'mvn package -DskipTests -B'
                sh 'docker build -t delivery .'
            }
        }
        stage ('Push') {
            when {
                anyOf {
                    not {
                        branch 'main'
                    }
                    environment name: 'PERFORM_RELEASE', value: 'true'
                }
                expression {
                    params.verifyPacts == false
                }
            }
            steps {
                sh """
                    docker tag delivery localhost:30010/delivery:${env.VERSION}
                    docker tag delivery localhost:30010/delivery:${env.BRANCH_NAME == 'main' ? 'stable' : 'latest'}
                    docker tag delivery localhost:30010/delivery:${env.GIT_COMMIT}
                    docker push localhost:30010/delivery:${env.VERSION}
                    docker push localhost:30010/delivery:${env.BRANCH_NAME == 'main' ? 'stable' : 'latest'}
                    docker push localhost:30010/delivery:${env.GIT_COMMIT}
                """
                script {
                    if (env.PERFORM_RELEASE.equals('true') && !env.RELEASE_VERSION.equals(env.SNAPSHOT_VERSION)) {
                        sh 'git config --global user.name "Jenkins"'
                        sh 'git config --global user.email "ci@openknowledge.de"'
                        sh "mvn scm:checkin -Dmessage='release of version ${env.RELEASE_VERSION}' -B"
                        sh "mvn scm:tag -Dtag=${env.RELEASE_VERSION} -B"
                        int nextRevision = Integer.parseInt(env.RELEASE_VERSION.substring(env.RELEASE_VERSION.lastIndexOf(".") + 1)) + 1
                        nextVersion = RELEASE_VERSION.substring(0, env.RELEASE_VERSION.lastIndexOf(".")) + "." + nextRevision + "-SNAPSHOT"
                        sh "sed -i 's/${env.RELEASE_VERSION}/${nextVersion}/g' deployment/overlays/prod/kustomization.yaml"
                        sh "mvn versions:set scm:checkin -DnewVersion=${nextVersion} -Dmessage='update version to ${nextVersion}' -B"
                    }
                }
            }
        }
        stage ('Deploy') {
            when {
                expression {
                    params.verifyPacts == false
                }
                anyOf {
                    not {
                        branch 'main'
                    }
                    environment name: 'PERFORM_RELEASE', value: 'true'
                }
            }
            steps {
                script {
                    if (env.PERFORM_RELEASE.equals('true') && !env.RELEASE_VERSION.equals(env.SNAPSHOT_VERSION)) {
                        sh "mvn scm:checkout -DscmVersion=${env.RELEASE_VERSION} -DscmVersionType=tag -B"
                        sh 'kubectl apply -k deployment/overlays/prod'
                    } else {
                        sh 'kubectl apply -k deployment/overlays/test'
                        sh "sed -i 's/${env.GIT_COMMIT}/${env.SNAPSHOT_VERSION}/g' deployment/overlays/test/kustomization.yaml"
                    }
                }
            }
        }
    }
}
