apiVersion: v1
kind: Service
metadata:
  name: delivery-service
spec:
  selector:
    app: delivery-service
  type: NodePort
  ports:
    - protocol: TCP
      port: 4002
      targetPort: 4002
      nodePort: 31080
      name: service
