apiVersion: v1
kind: Service
metadata:
  name: delivery-service
spec:
  selector:
    app: delivery-service
  type: NodePort
  ports:
    - protocol: TCP
      port: 4002
      targetPort: 4002
      nodePort: 30080
      name: service
---
apiVersion: v1
kind: Service
metadata:
  name: delivery-db
spec:
  selector:
    app: delivery-db
  type: NodePort
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      name: service
