apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
  - ../../base

patches:
  - target:
      version: v1
      kind: Service
      name: customer-service
    path: ./patches/port-patch.yaml

images:
 - name: customer
   newName: localhost:30010/customer
   newTag: 1.1.0-SNAPSHOT
