#!/usr/bin/env groovy

def computePreviousRevision(releaseVersion) {
    return Integer.parseInt(releaseVersion.substring(releaseVersion.lastIndexOf(".") + 1)) - 1;
}

def computePreviousVersion(previousRevision, releaseVersion) {
    return releaseVersion.substring(0, releaseVersion.lastIndexOf(".")) + "." + previousRevision
}

pipeline {
    agent any

    parameters {
        booleanParam(name: 'deployOnly', defaultValue: false, description: 'should this job just run to deploy a version')
        string(name: 'deploymentVersion', defaultValue: 'latest', description: 'which version should be deployed')
    }

    options {
        disableConcurrentBuilds()
    }

    environment {
        SNAPSHOT_VERSION = readMavenPom().getVersion()
        LAST_COMMIT_MESSAGE = "${currentBuild.changeSets.size() == 0 ? 'update version to ' : currentBuild.changeSets[currentBuild.changeSets.size() - 1].items.length == 0 ? 'update version to ' : currentBuild.changeSets[currentBuild.changeSets.size() - 1].items[currentBuild.changeSets[currentBuild.changeSets.size() - 1].items.length - 1].msg}"
        PERFORM_RELEASE = "${env.SNAPSHOT_VERSION.contains('-SNAPSHOT') && env.BRANCH_NAME == 'main' && !env.LAST_COMMIT_MESSAGE.startsWith('update version to ')}"
        RELEASE_VERSION = "${env.SNAPSHOT_VERSION.contains('-SNAPSHOT') ? env.SNAPSHOT_VERSION.substring(0, env.SNAPSHOT_VERSION.lastIndexOf('-SNAPSHOT')) : SNAPSHOT_VERSION}"
        VERSION = "${env.BRANCH_NAME == 'main' && !env.LAST_COMMIT_MESSAGE.startsWith('update version to ') ? env.RELEASE_VERSION : env.SNAPSHOT_VERSION}"
        PACT_VERSION = "${env.BRANCH_NAME == 'main' ? env.RELEASE_VERSION : env.RELEASE_VERSION + '+' + env.GIT_COMMIT}"
        STAGE = "${env.BRANCH_NAME == 'main' ? 'production' : 'test'}"
        DEPLOYMENT_VERSION = "${params.deploymentVersion != 'latest' ? params.deploymentVersion : env.VERSION}"
        PREVIOUS_REVISION = computePreviousRevision(env.RELEASE_VERSION)
        PREVIOUS_VERSION = computePreviousVersion(env.PREVIOUS_REVISION, env.RELEASE_VERSION)
    }

    triggers {
        pollSCM("* * * * *")
        GenericTrigger(
            genericRequestVariables: [
                [key: 'branch', regexpFilter: ''],
                [key: 'deployOnly', regexpFilter: ''],
                [key: 'deploymentVersion', regexpFilter: '']
            ],

            causeString: 'Triggered by web hook',

            token: 'customer-service',

            printContributedVariables: true,
            printPostContent: true,

            silentResponse: false,

            regexpFilterText: '$branch',
            regexpFilterExpression: ".*${(env.BRANCH_NAME == 'main' ? 'main' : 'develop')}.*"
        )
    }

    stages {
        stage ('Compile') {
            when {
                anyOf {
                    not {
                        branch 'main'
                    }
                    environment name: 'PERFORM_RELEASE', value: 'true'
                }
                expression {
                    params.deployOnly == false
                }
            }
            steps {
                echo "Building version ${env.VERSION}"
                script {
                    if (env.PERFORM_RELEASE.equals('true') && !env.RELEASE_VERSION.equals(env.SNAPSHOT_VERSION)) {
                        sh "mvn versions:set -DnewVersion=${env.RELEASE_VERSION} -B"
                    }
                }
                sh "mvn clean test-compile -B"
            }
        }
        stage ('Test') {
            when {
                anyOf {
                    not {
                        branch 'main'
                    }
                    environment name: 'PERFORM_RELEASE', value: 'true'
                }
                expression {
                    params.deployOnly == false
                }
            }
            steps {
                sh "mvn test -B"
            }
        }
        stage ('Upload pacts') {
            when {
                anyOf {
                    not {
                        branch 'main'
                    }
                    environment name: 'PERFORM_RELEASE', value: 'true'
                }
                expression {
                    params.deployOnly == false
                }
            }
            steps {
                sh "pact-broker publish target/pacts --broker-base-url=http://pact:9292 --consumer-app-version=${env.PACT_VERSION} --auto-detect-version-properties"
            }
        }
        stage ('Package') {
            when {
                anyOf {
                    not {
                        branch 'main'
                    }
                    environment name: 'PERFORM_RELEASE', value: 'true'
                }
                expression {
                    params.deployOnly == false
                }
            }
            steps {
                sh "mvn package meecrowave:bundle -Dservice.name=customer-service -DskipTests -B"
            }
        }
        stage ('Push') {
            when {
                anyOf {
                    not {
                        branch 'main'
                    }
                    environment name: 'PERFORM_RELEASE', value: 'true'
                }
                expression {
                    params.deployOnly == false
                }
            }
            steps {
                script {
                    if (env.PERFORM_RELEASE.equals('true') && !env.RELEASE_VERSION.equals(env.SNAPSHOT_VERSION)) {
                        sh """
                            sshpass -p 'jenkins' ssh -o "StrictHostKeyChecking=no" -p 2222 -q jenkins@prod 'mkdir -p ~/artifacts/customer-service/${env.RELEASE_VERSION}/'
                            sshpass -p 'jenkins' scp -o "StrictHostKeyChecking=no" -P 2222 -q target/customer-service*.zip jenkins@prod:/config/artifacts/customer-service/${env.RELEASE_VERSION}/
                            git config --global user.name 'Jenkins'
                            git config --global user.email 'ci@openknowledge.de'
                            mvn scm:checkin -Dmessage='release of version ${env.RELEASE_VERSION}' -B
                            mvn scm:tag -Dtag=${env.RELEASE_VERSION} -B
                        """
                        int nextRevision = Integer.parseInt(env.RELEASE_VERSION.substring(env.RELEASE_VERSION.lastIndexOf(".") + 1)) + 1
                        nextVersion = RELEASE_VERSION.substring(0, env.RELEASE_VERSION.lastIndexOf(".")) + "." + nextRevision + "-SNAPSHOT"
                        sh "mvn versions:set scm:checkin -DnewVersion=${nextVersion} -Dmessage='update version to ${nextVersion}' -B"
                    } else {
                        sh """
                            sshpass -p 'jenkins' ssh -o "StrictHostKeyChecking=no" -p 2222 -q jenkins@test 'mkdir -p ~/artifacts/customer-service/${env.SNAPSHOT_VERSION}/'
                            sshpass -p 'jenkins' scp -o "StrictHostKeyChecking=no" -P 2222 -q target/customer-service*.zip jenkins@test:/config/artifacts/customer-service/${env.SNAPSHOT_VERSION}/
                        """
                    }
                }
            }
        }
        stage ('Deploy') {
            when {
                expression {
                    script {
                        version = Integer.parseInt(env.PREVIOUS_REVISION) >= 0 ? env.PREVIOUS_VERSION : env.PACT_VERSION
                        def deploy = sh script: "pact-broker can-i-deploy --pacticipant=customer-service --version=${version} --to-environment=${env.STAGE} --broker-base-url=http://pact:9292", returnStatus: true
                        return deploy == 0
                    }
                }
                anyOf {
                    not {
                        branch 'main'
                    }
                    environment name: 'PERFORM_RELEASE', value: 'true'
                    expression {
                        params.deployOnly == true
                    }
                }
            }
            steps {
                script {
                    if (env.STAGE == 'production') {
                        sh "sshpass -p 'jenkins' ssh -o 'StrictHostKeyChecking=no' -p 2222 -q jenkins:jenkins@prod '[ -f ~/customer-service-distribution/bin/meecrowave.sh ] && ~/customer-service-distribution/bin/meecrowave.sh stop && rm -rf ~/customer-service-distribution/; unzip ~/artifacts/customer-service/${env.DEPLOYMENT_VERSION}/customer-service-meecrowave-distribution.zip -d ~/; nohup ~/customer-service-distribution/bin/meecrowave.sh start --http=8081'"
                    } else {
                        sh "sshpass -p 'jenkins' ssh -o 'StrictHostKeyChecking=no' -p 2222 -q jenkins:jenkins@test '[ -f ~/customer-service-distribution/bin/meecrowave.sh ] && ~/customer-service-distribution/bin/meecrowave.sh stop && rm -rf ~/customer-service-distribution/; unzip ~/artifacts/customer-service/${env.DEPLOYMENT_VERSION}/customer-service-meecrowave-distribution.zip -d ~/; nohup ~/customer-service-distribution/bin/meecrowave.sh start --http=8081'"
                    }
                    version = Integer.parseInt(env.PREVIOUS_REVISION) >= 0 ? env.PREVIOUS_VERSION : env.PACT_VERSION
                    sh "pact-broker create-or-update-pacticipant --broker-base-url=http://pact:9292 --name=customer-service --main-branch=main"
                    sh "pact-broker create-or-update-version --broker-base-url=http://pact:9292 --pacticipant=customer-service --version=${version}"
                    sh "pact-broker record-deployment --broker-base-url=http://pact:9292 --pacticipant=customer-service --environment=${env.STAGE} --version=${version}"
                }
            }
        }
    }
}
